version: "3.7"
services:
  db:
    image: mongo
    container_name: runaway_db
    volumes:
      - db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: runaway
    networks:
      - backend
    ports:
      - "27017:27017"

  app:
    image: node:12-alpine
    container_name: runaway_app
    volumes:
      - ./dist:/app/dist
      - ./bin:/app/bin
      - ./node_modules:/app/node_modules
    environment:
      - MONGO_URI='mongodb://root:example@db:27017/'
    restart: always
    networks:
      - backend
    depends_on:
      - db
    command: node /app/bin/www
    ports:
      - "3000:3000"

networks:
  backend:

volumes:
  db-data:
    name: runaway-data
