version: "3.7"
services:
  db:
    image: mongo
    volumes:
      - db-data:/data/db
    environment:
      # - AUTH=no
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend
    ports:
      - "27017:27017"

  app:
    image: node:12-alpine
    volumes:
      - ./dist:/app/dist
      - ./bin:/app/bin
      - ./node_modules:/app/node_modules
    environment:
      - MONGO_URI="mongodb://db:27017/app"
    restart: always
    networks:
      - backend
    depends_on:
      - db
    command: node /app/bin/www
    ports:
      - "3000:3000"

networks:
  backend:

volumes:
  db-data:
