version: '3.7'
services:
    app:
        working_dir: /app
        image: node:12-alpine
        container_name: runaway_app
        volumes:
            - ./dist:/app/dist
            - ./public:/app/public
        # environment:
        # - MONGO_URI='mongodb://root:example@db:27017/'
        restart: always
        command: node /app/dist/index.js
        ports:
            - '3000:3000'
